# Generated by Django 5.0.9 on 2024-11-23 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_informacionanalizada_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisSimilitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('porcentaje_similitud', models.DecimalField(decimal_places=2, max_digits=5)),
                ('informacion_analizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.informacionanalizada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
