# Generated by Django 5.0.9 on 2024-11-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_analisissimilitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisissimilitud',
            name='usuario',
        ),
    ]
